utils/db.js
Dear Zeyna,
I have created a new branch and worked on the database. Here are the key update in this pull request:
-the database is created
Please review the code and let me know if you have any feedback or suggestions for improvement. I'm open to making any necessary modifications to ensure the quality and functionality of the feature.
Thank you!
=> database is ready to be used

app/courses/page.jsx, components/ListElement.js
I have designed the component element and added the database and functions with Zeyna
=> Feat: List element component added

app/courses/page.jsx, components/Details.jsx, components/ListElement.jsx, styles/globals.css
I and Zeyna  worked on the component design and functions of fetching the data from the local database
=> feat: Details component added

components/Nav.jsx
style:navbar style added to components folder
TODO:navbar style needs to be implemented to global css
=> feat: navbar component added

app/profile/page.jsx, components/InfoBar.jsx, package-lock.json
style:InfoBar is styled with tailwind
=> feat: info component for the profile page added

app/page.js
style of the intro page added , 
todo : sign up component
=> style: intro page added

app/profile/page.jsx, app/statistics/page.jsx, components/FinishedCourses.jsx
style:the finished courses card component styled with tailwind TODO:complete the rest cards of profile statistics
=> feat:profile statistic card added

app/statistics/page.jsx, components/StatisticsGoalSreak.jsx, components/StatisticsGoalStreak.jsx
check the "statistics/ goal and streak" 
styling is needed. 
icons must be added.
=> feat: statistics goal and steak

app/layout.js, components/Nav.jsx
=> feat: navbar hidden from intro page

app/home/page.jsx, components/HomeCategory.jsx
=> home category added

app/profile/page.jsx, components/Achievements.jsx, components/StatisticsGoalStreak.jsx
achievements main objects added , 
further styling needed,
=> achievments objects added

app/page.js, app/profile/page.jsx, components/Intro.jsx, components/Login.jsx
sign in input added , 
further styling needed ,
=> 99 introloginlogout component

app/courses/page.jsx, app/saved/page.jsx, components/Details.jsx, components/ListElement.jsx, components/SavedCourseReview.jsx, components/SavedCourses.jsx, utils/db.js
=> Feat: The saved page is added

app/page.js, components/Login.jsx, components/RegistrationForm.jsx
Registration form added , 
further styling needed ,
=> registration form added

components/Achievements.jsx
colors must be modified , 
sports cupa must be added ,
=> more styling: done

app/home/page.jsx, components/MyLearning.jsx
The home Page design is done, please check it guys.
Happly hear the feedback from u!
=> Home Page Design finished

app/statistics/page.jsx, components/StatisticsGoalStreak.jsx
size of cards and boxes must be modified , 
icons size and shapes must be same as original,
=> Goal and streak styling

components/StatisticsGoalStreak.jsx
coloring: done . 
icons :  still not identical to the original page.
=> Goal and streak:edit

app/page.js, app/pages/api/getCourses.js, components/Achievements.jsx
identical colors added .
styles finished , 
icons : must be found and added. (cupa)
=> edit colors and style : acievments component

components/Achievements.jsx
correct  colors  added , 
styling finished, 
icons must be identical to the original , 
cupa icon must be found and added
=> achievements coloring and styling

app/pages/profile/page.jsx, components/Achievements.jsx, utils/achievementsData.js
Style:the acheivment component code is changed according to the added acheivmentData file
=> Feat:acheivment database is added

app/pages/profile/page.jsx, components/Friends.jsx
=> friends component

components/Login.jsx, components/firebase.jsx
-Set up authentication in the firebase
-Connect the firebase with the project
=> Feat: set-up-authentication-in-firebase

app/pages/courses/page.jsx, components/Details.jsx, components/ListElement.jsx, components/SavedCourseReview.jsx, components/SavedCourses.jsx
The style of the saved page is added
=> Style: the style of saved page added

app/pages/profile/page.jsx, components/InfoBar.jsx, utils/InfoBarData.js
Style:added some changes in the style classes of profile page and InfoBar component
=> Feat: the data of InfoBar component added in InfoBarData.js

app/pages/profile/page.jsx, components/FriendsSuggestion.jsx
Fix:the profile page overlab fixed
=> Feat:FriendsSuggestion component added

utils/FriendsSuggestionData.js
=> Feat:the data of FriendsSuggestion componet added in FriendsSuggestionData.js

components/ListElement.jsx
The statistics button added to the course page
=> Feat: statistics button added

app/pages/statistics/page.jsx, components/Activities.jsx, components/MyActivitiesBox.jsx, utils/MyActivityData.js
my activities :
my activity box : done 
my activity utils data : done
=> my activity and my activity box done

app/pages/statistics/page.jsx, components/LastYearComparison.jsx, components/LastYearComponentContainer.jsx
Last Year Comparison component
=> Last Year Comparison

app/pages/statistics/page.jsx, components/ThisWeek.jsx, components/ThisWeekContainer.jsx
This week : added / included in statistics page.
=> This week component modified

components/Details.jsx, components/ListElement.jsx, components/SavedCourseReview.jsx, components/SavedCourses.jsx, styles/globals.css
Scroll was added to the saved and courses page
the function of rendering courses fixed
=> 202 adding scroll to the courses and saved page

app/page.js, components/GetStarted.jsx, package-lock.json, package.json, utils/firebase.js
feat: adding userdoc to users collection, data from google and country from ip api 
todo: edit reference of doc to uid
=> feat:save userdata to db from google authentication

app/pages/statistics/page.jsx, components/MyPerformance.jsx
My Performance component added to Statistical page
=> MyPerformance component

components/Details.jsx, components/ListElement.jsx, components/SavedCourseReview.jsx, components/SavedCourses.jsx, styles/globals.css
The function of the save button added to the "ListElement"
=> Feat: the function of the saved button added

app/pages/home/page.jsx, components/FeaturedCourses.jsx, components/HomeCategories.jsx, components/MyLearning.jsx
-I fixed the home page designed 
-Couldn't fix the image corner issue and "My Learning" comp saved button.
=> Home page redesigned

components/Details.jsx, components/ListElement.jsx, components/Loading.jsx, components/SavedCourseReview.jsx, components/SavedCourses.jsx
Me and Zeyna made the course page responsive
=> The user name added to the "Details.js" and "SavedCoursePreview.js"

components/ListElement.jsx, components/NoCourseMessage.jsx, components/SavedCourses.jsx
no saved courses message component added
Focus property added to the courses div in the courses and saved pages
=> 231 create no saved courses message component

app/pages/home/page.jsx, components/HomeCategories.jsx
=> Home Categories done

app/pages/statistics/page.jsx, components/Activities.jsx, components/HomeCategories.jsx, components/LastYearComparison.jsx, components/MyActivitiesBox.jsx, components/MyPerformance.jsx
=> padding fixed

app/pages/statistics/page.jsx
fixing statistics page components padding , 
please check it with your screen ,
=> fixing statistics page

app/pages/courseDetail/page.jsx, components/CourseOverview.jsx, next.config.js, package-lock.json, package.json
the extension button on svg added ,but couldn't bring the data from firebase
=> Feat:course overview component added

components/CourseOverview.jsx
=> Fix:the dropdown button list fixed and styled
